[package]
name = "afec-explorer"
version = "0.2.0"
description = "Experimental GUI for browsing AFEC high-level databases"
authors = ["emuell"]
license = "GPL v3"
repository = ""
edition = "2021"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2", features = [] }

[dependencies]

# common
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
log = { version = "^0.4", features = [
    "max_level_debug",
    "release_max_level_info",
] }
simplelog = { version = "^0.12" }
crossbeam-channel = { version = "0.5" }
anyhow = { version = "1.0" }

#tauri
tauri = { version = "~2.8", features = [] }
tauri-plugin-window-state = { version = "^2" }
tauri-plugin-sql = { version = "^2", features = ["sqlite"] }
tauri-plugin-dialog = { version = "^2" }

# audio
phonic = { git = "https://github.com/emuell/phonic" }

# tsne
rstats = { version = "^2.1" }
bhtsne = { version = "^0.5" }
# use version from tauri-plugin-sql
sqlx = { version = "*", features = ["sqlite", "macros"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
