// -------------------------------------------------------------------------------------------------

/* Single converted row in an AFEC high level database */

export interface File {
	filename: string,
	modtime: number,
	// status: string,
	file_type_S: string,
	file_size_R: number,
	file_length_R: number,
	file_sample_rate_R: number,
	file_channel_count_R: number,
	file_bit_depth_R: number,
	// class_signature_VR: number[],
	classes_VS: string[],
	// class_strengths_VR: number[],
	categories_VS: string[],
	// category_strengths_VR: number[],
	base_note_R: number,
	base_note_confidence_R: number,
	peak_db_R: number,
	rms_db_R: number,
	bpm_R: number,
	bpm_confidence_R: number,
	brightness_R: number,
	noisiness_R: number,
	harmonicity_R: number,
	// spectrum_signature_VVR: number[][],
	spectral_flatness_R: number,
	spectral_flux_R: number,
	spectral_complexity_R: number,
	spectral_contrast_R: number,
	spectral_inharmonicity_R: number,
	// pitch_VR: number[],
	pitch_confidence_R: number,
	// peak_VR: number[],
}

/* sqlite column names of interface File */

export const fileColumnNames = [
	"filename",
	"modtime",
	"file_type_S",
	"file_size_R",
	"file_length_R",
	"file_sample_rate_R",
	"file_channel_count_R",
	"file_bit_depth_R",
	"classes_VS",
	"categories_VS",
	"base_note_R",
	"base_note_confidence_R",
	"peak_db_R",
	"rms_db_R",
	"bpm_R",
	"bpm_confidence_R",
	"brightness_R",
	"noisiness_R",
	"harmonicity_R",
	"spectral_flatness_R",
	"spectral_flux_R",
	"spectral_complexity_R",
	"spectral_contrast_R",
	"spectral_inharmonicity_R",
	"pitch_confidence_R",
];