// -------------------------------------------------------------------------------------------------

/* Single converted row in an AFEC high level database */

export interface File {
	filename: string,
	modtime: number,
	status: string,
	file_type_S: string,
	file_size_R: number,
	file_length_R: number,
	file_sample_rate_R: number,
	file_channel_count_R: number,
	file_bit_depth_R: number,
	class_signature_VR: number[],
	classes_VS: string[],
	class_strengths_VR: number[],
	category_signature_VR: number[],
	categories_VS: string[],
	category_strengths_VR: number[],
	base_note_R: number,
	base_note_confidence_R: number,
	peak_db_R: number,
	rms_db_R: number,
	bpm_R: number,
	bpm_confidence_R: number,
	brightness_R: number,
	noisiness_R: number,
	harmonicity_R: number,
	spectrum_signature_VVR: number[][],
	spectral_flatness_R: number,
	spectral_flux_R: number,
	spectral_complexity_R: number,
	spectral_contrast_R: number,
	spectral_inharmonicity_R: number,
	pitch_VR: number[],
	pitch_confidence_R: number,
	peak_VR: number[],
}
